require 'spec_helper'

describe Spree::Category do
  context "validation" do
    let(:category) { build :category }
    it "should be valid without a description" do
      expect(category).to be_valid
    end

    it "should have an unique name" do
      another_category = create :category, name: "sport"
      expect(category).not_to be_valid
    end
  end

  context "permalink" do
    let(:category) { create :category }
    it "should be generated by name" do
      expect(category.permalink).to eq(category.name.to_s.to_url)
    end
  end
end
